name: ESP32 Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build project using Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/project -w /project espressif/idf:v5.1.1 \
        bash -c "idf.py set-target esp32 && idf.py build"